### ISSUE TITLE
An inquiry

### ISSUE THREAD

**Issue by song201216** [fenglinglwb/MAT#1]
Hello, I'm not quite understand this ws is used for
![image](https://user-images.githubusercontent.com/73896789/161255003-a731ff2f-d426-44e9-906d-7003dd02ac23.png)

**Comment by fenglinglwb** [comment]
The 'ws' mapped from Gaussian noise serves as the noise style, which is then used in the style manipulation module.

**Comment by song201216** [comment]
Thank you. You've been very helpful.
