### ISSUE TITLE
AssertionError on custom trained model inference

### ISSUE THREAD

**Issue by kzafeir** [fenglinglwb/MAT#108]
Hello @fenglinglwb and congratulations for the excellent work the pretrained models are working fine I also trained my own model and did so successfully with no errors however when I tried to use it for inference I got the following error:

(matenv2) C:\Users\user\PycharmProjects\MAT>python generate_image.py --network pretrained/network-snapshot-000000.pkl --dpath "C:\Users\user\tensorflow_datasets\merced1TAG\train512" --mpath "C:\Users\user\tensorflow_datasets\merced1TAG\train512" --outdir OUTPUT/CUSTOOOOOMMMMM                                                         Loading data from: C:\Users\user\tensorflow_datasets\merced1TAG\train512                                       Loading mask from: C:\Users\user\tensorflow_datasets\merced1TAG\train512                                       Loading networks from: pretrained/network-snapshot-000000.pkl                                                        Traceback (most recent call last):                                                                                     File "generate_image.py", line 156, in <module>                                                                        generate_images() # pylint: disable=no-value-for-parameter                                                         File "C:\Users\user\AppData\Local\anaconda3\envs\matenv2\lib\site-packages\click\core.py", line 1157, in __call__                                                                                                                     return self.main(*args, **kwargs)                                                                                  File "C:\Users\user\AppData\Local\anaconda3\envs\matenv2\lib\site-packages\click\core.py", line 1078, in main    rv = self.invoke(ctx)                                                                                              File "C:\Users\user\AppData\Local\anaconda3\envs\matenv2\lib\site-packages\click\core.py", line 1434, in invoke                                                                                                                       return ctx.invoke(self.callback, **ctx.params)                                                                     File "C:\Users\user\AppData\Local\anaconda3\envs\matenv2\lib\site-packages\click\core.py", line 783, in invoke                                                                                                                        return __callback(*args, **kwargs)                                                                                 File "C:\Users\user\AppData\Local\anaconda3\envs\matenv2\lib\site-packages\click\decorators.py", line 33, in new_func                                                                                                                 return f(get_current_context(), *args, **kwargs)                                                                   File "generate_image.py", line 103, in generate_images                                                                 copy_params_and_buffers(G_saved, G, require_all=True)                                                              File "generate_image.py", line 46, in copy_params_and_buffers                                                          assert (name in src_tensors) or (not require_all)                                                                AssertionError                                                                 

I have also noticed that when trained both my 512 and 256 models are a different size than your pretrained models more specifically:

256:  pretrained: 627.272KB / mine: 614.938KB
512:  pretrained: 645.930KB / mine: 633.593KB 

I have trained my 512model for example like this:
python train.py ^
    --outdir=C:\Users\user\PycharmProjects\MAT\mercedmodel ^
    --gpus=1 ^
    --batch=1 ^
    --metrics=fid36k5_full ^
    --data=C:\Users\user\tensorflow_datasets\merced1TAG\train512^
    --data_val=C:\Users\user\tensorflow_datasets\merced1TAG\val512 ^
    --dataloader=datasets.dataset_512.ImageFolderMaskDataset ^
    --mirror=True ^
    --cond=False ^
    --cfg=auto ^
    --aug=noaug ^
    --generator=networks.mat.Generator ^
    --discriminator=networks.mat.Discriminator ^
    --loss=losses.loss.TwoStageLoss ^
    --pr=0.1 ^
    --pl=False ^
    --truncation=0.5 ^
    --style_mix=0.5 ^
    --ema=10 ^
    --lr=0.001

It is also noteworthy that I have commented out lines 413-421 from training_loop.py because I was getting an index error in the training it shouldn't however have any effect in the final result since it is only for reporting metrics. I have also reduced the number of kimg in each tick to 1 and the total number of ticks to 2 this too however should be inconsequential to the final pickle file size. Any ideas as to what may cause this?

Thank you

**Comment by kzafeir** [comment]
I fixed the issue by setting 'require_all' to False in generate_image.py in line 103

**Comment by qwexacc** [comment]
Hello, I am a novice, I would like to ask you about the production process of data sets, can you guide me? Thank you very much!
