### ISSUE TITLE
CUDA issue

### ISSUE THREAD

**Issue by Iraanol** [fenglinglwb/MAT#11]
Hi, I tried to run my dataset based on the pretrained model. However, I got this error : 

 Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

 when running : python generate_image.py --network pretrained/CelebA-HQ.pkl --dpath test_sets/CelebA-HQ/images --mpath test_sets/CelebA-HQ/masks --outdir samples
 
 What should I do?

**Comment by fenglinglwb** [comment]
Please check whether the GPU is available.
