### ISSUE TITLE
regarding mask updation strategy

### ISSUE THREAD

**Issue by gargatik** [fenglinglwb/MAT#15]
hi,

can you tell me role of these three lines in mask updation?

![Screenshot 2022-05-25 170533](https://user-images.githubusercontent.com/78840940/170226100-bece0834-45f8-4c84-9025-a3fd0379ec5b.png)

**Comment by fenglinglwb** [comment]
This is the implementation of partial convolution. Please refer to https://github.com/NVIDIA/partialconv/blob/master/models/partialconv2d.py.

**Comment by Just-Eating** [comment]
> 

It seems  the partial conv rather the mask updating strategy described in the paper.  Do you use the mask updateing strategy in the transformer block ? I am also very confused about it.

**Comment by fenglinglwb** [comment]
In transformer blocks, the mask is updated in https://github.com/fenglinglwb/MAT/blob/c2a46c928a1bd6e5501135c56b10b686e287ba22/networks/mat.py#L159-L164
