### ISSUE TITLE
Quick Test have some questions

### ISSUE THREAD

**Issue by liuxingyu123** [fenglinglwb/MAT#17]
`Setting up PyTorch plugin "bias_act_plugin"... Failed!
..\torch_utils\ops\bias_act.py:50: UserWarning: Failed to build CUDA kernels for bias_act. Falling back to slow reference implementation. Details:

Traceback (most recent call last):
  File "..\torch_utils\ops\bias_act.py", line 48, in _init
    _plugin = custom_ops.get_plugin('bias_act_plugin', sources=sources, extra_cuda_cflags=['--use_fast_math'])
  File "..\torch_utils\custom_ops.py", line 64, in get_plugin
    raise RuntimeError(f'Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "{__file__}".')
RuntimeError: Could not find MSVC/GCC/CLANG installation on this computer. Check _find_compiler_bindir() in "..\torch_utils\custom_ops.py".`
hello，I didn't download vs. what is the specific solution to this problem

**Comment by fenglinglwb** [comment]
If you were using Windows, please refer to https://github.com/RameenAbdal/StyleFlow/issues/13.

**Comment by fenglinglwb** [comment]
I find a solution. Just use Miniconda or Conda to first install the Pytorch as
`conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 tensorboard -c pytorch --yes`
and then install the required libs. It works.

**Comment by liuxingyu123** [comment]
hello，it works，but when i run test code ， it stucks on Setting up PyTorch plugin "upfirdn2d_plugin"
`Loading data from: test_sets/CelebA-HQ/images
Loading mask from: test_sets/CelebA-HQ/masks
Loading networks from: pretrained/CelebA-HQ_512.pkl
Prcessing: test1.png
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... `
Is there a solution.

**Comment by liuxingyu123** [comment]
it works ，but when i run the test code ，it stucks on Setting up PyTorch plugin "upfirdn2d_plugin"
`Loading data from: test_sets/CelebA-HQ/images
Loading mask from: test_sets/CelebA-HQ/masks
Loading networks from: pretrained/CelebA-HQ_512.pkl
Prcessing: test1.png
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... `
Is there a solution?

**Comment by liuxingyu123** [comment]
thank you very much，it  works .but My GPU performance is not very good. Do you have any solutions
`RuntimeError: CUDA out of memory. Tried to allocate 180.00 MiB (GPU 0; 2.00 GiB total capacity; 964.18 MiB already allocated; 0 bytes free; 1.18 GiB reserved in total by PyTorch)`

**Comment by fenglinglwb** [comment]
I am sorry that the 2G memory of the GPU may not be sufficient to process 512x512 images.
