### ISSUE TITLE
能否写个colab运行demo?

### ISSUE THREAD

**Issue by Baiyuetribe** [fenglinglwb/MAT#18]
本地环境一堆报错，放弃了。希望可以简单出个最小demo
```
ImportError: DLL load failed while importing upfirdn2d_plugin: 找不到指定的模块。
warnings.warn('Failed to build CUDApython generate_image.py --network pretrained/CelebA-HQ_512.pkl --dpath test_sets/CelebA-HQ/images --mpath test_sets/CelebA-HQ/masks --outdir
```

**Comment by fenglinglwb** [comment]
If you use Conda to install the environment, it would be quite easy. You can try it.

**Comment by fenglinglwb** [comment]
Hi, have you successfully managed the environment? If not, you may visit https://replicate.com/fenglinglwb/large-hole-image-inpainting (provided by Replicate) for a reference. Not sure if it is correct or not. You are recommended to use our models as described.
