### ISSUE TITLE
How long for the training time?

### ISSUE THREAD

**Issue by LonglongaaaGo** [fenglinglwb/MAT#23]
Hi @fenglinglwb.
Thank you so much for your awesome work.
Could you tell me about the training time for CelebA-HQ 512 and Place2 512 datasets?
Another question is why finally you set 1.8 M for training the place2 dataset, instead of others, e.g. 2.M 1.M 3.5M, etc?

Thanks!

**Comment by fenglinglwb** [comment]
We trained the Places2 model for nearly two weeks and CelebA-HQ 512 is halved, using A100.

We initially adopted the Places-Standard dataset for training, which contains 1.8M images.

**Comment by LonglongaaaGo** [comment]
Hi @fenglinglwb ,
OK, got it!
Thank you so much!

**Comment by UdonDa** [comment]
@fenglinglwb 
Hi,
>We trained the Places2 model for nearly two weeks and CelebA-HQ 512 is halved, using A100.

You mean when you usea single A100, you can train CelebA-HQ 512 model for a week?

In my environment, I need 500 hours using  four A100 GPUs to train 25M images...

**Comment by fenglinglwb** [comment]
We use 8 A100 GPUs o train 25M images for nearly 8.5-9.0 days.

**Comment by UdonDa** [comment]
Oh, incredible...
