### ISSUE TITLE
Why do use the same checkpoint to eval on the PID and UID  twice or more, and the results are different?

### ISSUE THREAD

**Issue by xinxinxing** [fenglinglwb/MAT#27]
Congratulations on CVPR2022 Best Paper Finalists!!

Why do use the same checkpoint to eval on the PID and UID  twice or more, and the results are different?

**Comment by fenglinglwb** [comment]
If you use different devices or random seeds to test the model, the result may be different.

**Comment by xinxinxing** [comment]
Thank you for your answer！ Further, I would like to ask what is the best random seed about the eval. And I found that different random seeds have a great impact on the results.

**Comment by fenglinglwb** [comment]
When evaluating quantitative metrics, I always set the seed to 0.

**Comment by xinxinxing** [comment]
Thank you for your answer！
