### ISSUE TITLE
During inference, does your Generator model takes the ground truth image as the input? 

### ISSUE THREAD

**Issue by AllenEdgarPoe** [fenglinglwb/MAT#28]
Image inpainting is a task of completing holes of the image. Thus, during inference, when there is no ground truth image, the generator should only pass through the masked image as an input. But your code in 'generate_image.py' seems as if it passes through the ground truth image as well. 

image = `read_image(ipath)`
`output = G(image, mask, z, label, truncation_psi=truncation_psi, noise_mode=noise_mode)` 

So, I took an experiment with your pretrained 'CelebA-HQ' (256) model and passed through two different images; **masked image** and the **ground truth image** for the `image` as the `G` 's component. 

Then, it seems as if the model's output is largely affected by the image of the input. 
For the below image, the left one is the input image, the middle one is the masked image, and the right one is the output. 

![267](https://user-images.githubusercontent.com/43398106/183365146-aac943e7-5399-494f-8730-37bfdba708e4.jpg)
![267_gt](https://user-images.githubusercontent.com/43398106/183365157-8523c338-3db9-4825-bcda-97b11e16f374.jpg)
![1400](https://user-images.githubusercontent.com/43398106/183365200-b2ad1161-0b1f-4c8d-9d58-e1c07886d552.jpg)
![1400_gt](https://user-images.githubusercontent.com/43398106/183365209-8c74bc4d-f928-4f71-ab4e-bfec3cd73d9e.jpg)
![8755](https://user-images.githubusercontent.com/43398106/183365373-9cad6751-89f7-4340-ae49-627477b32983.jpg)
![8755_gt](https://user-images.githubusercontent.com/43398106/183365385-38a8796c-91ef-49d6-8432-a3badd8062b6.jpg)

Can you please tell me how the ground truth image affects the results of the inference?

**Comment by fenglinglwb** [comment]
We didn't take the GT as the input. The image was masked in the https://github.com/fenglinglwb/MAT/blob/e5b9ca73d2bee044d8c546c7d99200deedc7fd17/networks/mat.py#L754
and
https://github.com/fenglinglwb/MAT/blob/e5b9ca73d2bee044d8c546c7d99200deedc7fd17/networks/mat.py#L834

**Comment by AllenEdgarPoe** [comment]
The difference was due to the different pixel value of the mask.. The mask contained certain pixels which are not denoted with 0 or 1. It was because the mask was interpolated into smaller image size.
