### ISSUE TITLE
FFHQ weights

### ISSUE THREAD

**Issue by sam-motamed** [fenglinglwb/MAT#35]
Thank you for the great work. 

Do you happen to have the weights for FFHQ that you could share?

**Comment by fenglinglwb** [comment]
Thanks for your interest. So far we don't have a model for FFHQ. But I could train one.

**Comment by sam-motamed** [comment]
Question was answered

**Comment by sam-motamed** [comment]
Would it be possible for you to also provide 512 * 512 FFHQ weights? With my current resources, I do not think I can train one myself

**Comment by fenglinglwb** [comment]
Ok, I will train a model on 512 * 512 FFHQ. It may take some time.

**Comment by sam-motamed** [comment]
Hello. Wondering if there was any updates on this? 🙌

**Comment by fenglinglwb** [comment]
It's almost done, about 3 days left.

**Comment by fenglinglwb** [comment]
We have provided the model. Thanks.

**Comment by sam-motamed** [comment]
12/1p paper support! thank you so much

**Comment by sam-motamed** [comment]
BTW, I notice W projection is much slower on FFHQ loaded model! any idea why?

**Comment by fenglinglwb** [comment]
Weird, it should be the same.

**Comment by sam-motamed** [comment]
Yes really odd! noticeably slower vs CelebA
