### ISSUE TITLE
Pretrained Model on Places2

### ISSUE THREAD

**Issue by lyumingzhi** [fenglinglwb/MAT#36]
Hi! Very impressed on your Great work. Currently, I am doing research on Inpainting models on Places2 dataset. I find there is only pretrained model on Places dataset. May I know if there is a pretrained model on Places2?

**Comment by fenglinglwb** [comment]
Thanks for your interest. In my view, Places (8M images) is also denoted as Places 2. So is there any difference?

**Comment by lyumingzhi** [comment]
Oh I see. Sorry for the misunderstanding. I try the Place pretrained model on Places2, but it behaves unnormal so I thought it was not trained on Places2. But I change the preprocessing procedure a little bit, then everything works perfectly. Thank you very much for your instant reply!

**Comment by fenglinglwb** [comment]
Hope you are going well.
