### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by UdonDa** [fenglinglwb/MAT#5]
Hi, @fenglinglwb!

Thank you for your sharing your nice code. Congratulations on CVPR22!

I wonder how to quantitively evaluate generated images.
Which images, which are generated images or blended images, did you use?

I succeed to generate samples, but, generated images include some artifacts caused by input mask pixels.

Left: a generated image. Right: blended images using input and generated images.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/25411643/161925519-35dbc69c-1cb6-402d-9906-bb6481f53a89.png">

**Comment by fenglinglwb** [comment]
Following previous work, we use the blended result for evaluation. Also, during training, the discriminator only looks at the blended result, thus being unreasonable to use the generated result.

**Comment by UdonDa** [comment]
I know. Thank you!
