### ISSUE TITLE
关于metrics中协方差矩阵疑惑

### ISSUE THREAD

**Issue by worhar** [fenglinglwb/MAT#51]
您好，感谢您的工作，它对我帮助很大。
我在阅读FID的计算方式时候，发现您的计算过程是sum(x64.T@x64) / nums - np.outer(mean, mean)，这和在网上查到的协方差计算过程不一致，您的实现方式是否是另一种方法？
期待您的回答。

**Comment by fenglinglwb** [comment]
This is the implementation of stylegan-ada-pytorch.

**Comment by worhar** [comment]
您知道为什么可以这么算吗，我感觉和使用np.cov()来计算结果是不一样的，我刚刚尝试寻找了一下，但没找到相关的说明。
我在CoModGan发现它使用的是np.cov()。

**Comment by fenglinglwb** [comment]
Not sure about it. But all models are evaluated using the same script, thus being fair comparisons in our paper.

**Comment by worhar** [comment]
明白了，感谢您的解答。
