### ISSUE TITLE
an issue when running the metric

### ISSUE THREAD

**Issue by rose-jinyang** [fenglinglwb/MAT#52]
Hello
How are you?
Thanks for contributing to this project.
I have 40K samples as training images without mask and 10K samples as validation images without mask.
I am going to train my own model on this dataset.
I have an issue at the step when running the metric.

![image](https://user-images.githubusercontent.com/47862419/208432473-31a3dd1b-f992-4080-8b5d-ce6fde7f991f.png)

It seems that's because the index is greater than the number of the validation samples.
Could u guide me to fix this issue?
Thanks

**Comment by fenglinglwb** [comment]
Please check the metric you used. For example, when adopting 'fid36k5', you need to prepare 36.5k images. Just select or re-define a proper metric.

**Comment by rose-jinyang** [comment]
Thanks for your quick reply.
