### ISSUE TITLE
Training with only black mask on ground truth

### ISSUE THREAD

**Issue by vichi06** [fenglinglwb/MAT#54]
Hi, 

I have been training MAT on custom dataset of 1100 images, but it seems like there is a problem because the results are not good. 
I was wondering why in the first fake00000 snapshot, the masks are colored with different colors ? My input should be a black mask. 

fake00000 :
![image](https://user-images.githubusercontent.com/56552964/211969111-82dbbd74-6b38-4dfc-b27d-a587f556cae0.png)

results after 10 epochs :
![image](https://user-images.githubusercontent.com/56552964/211969128-8d1c6f93-5561-4144-b9b6-5adc73e9658f.png)

Kind regards.

**Comment by fenglinglwb** [comment]
The fake results are produced by the randomly initialized network. Thus, the inpainted area could be colorful.

**Comment by vichi06** [comment]
> The fake results are produced by the randomly initialized network. Thus, the inpainted area could be colorful.

Okay, but I have been modifying dataset_256.py like this to train the model depending on my custom masks. 

![Screenshot at 2023-01-12 14-33-08](https://user-images.githubusercontent.com/56552964/211985747-3337e5ee-0c4a-461d-892b-6a70f4978ff8.png)

Do you have any idea why the results are that bad ? 

Thanks for the quick answer. 
Kind regards.

**Comment by fenglinglwb** [comment]
Maybe the dataset with 1100 images is not sufficient to train a large model.

**Comment by vichi06** [comment]
> Maybe the dataset with 1100 images is not sufficient to train a large model.

Okay thank you @fenglinglwb I will look more through it...

**Comment by anushka17agarwal** [comment]
@vichi06 How are you training the model on custom code?
