### ISSUE TITLE
How can I use 512x512 pretrained model to inpaint 1024x1024 images?

### ISSUE THREAD

**Issue by Matthewhouch** [fenglinglwb/MAT#6]
Hi! Thanks for the great work.
Tough I have some little questions, as you said in readme : 

> "Our implementation only supports generating an image whose size is a multiple of 512. You need to pad or resize the image to make its size a multiple of 512. Please pad the mask with 0 values."

So I use generate_image.py and set --resolution into  1024 , with 512x512 pretrained model you offered, but it seems not working out. The error is below:

> File "MAT-main/networks/mat.py", line 20, in nf
>     return NF[2 ** stage]
> KeyError: 1024

It seems that it lacks parameters for 1024x1024 resolution, how can I solve this? Or to say, how can I use 512x512 pretrained model to inpaint 1024x1024 images as you said?

**Comment by fenglinglwb** [comment]
Hi, thanks for your attention! Actually, we should always build the model with a resolution of 512x512, no matter what the input size is. I have fixed this problem. Please pull the latest version.

Although our Places model can handle 1024x1024 images, we suggest maintaining resolution consistency during
training and testing yield better visual quality.

**Comment by fenglinglwb** [comment]
Hi, thanks for your attention! Actually, we should always build the model with a resolution of 512x512, no matter what the input size is. I have fixed this problem. Please pull the latest version.

Although our Places model can handle 1024x1024 images, we suggest maintaining resolution consistency during
training and testing yield better visual quality.

**Comment by fenglinglwb** [comment]
Hi, thanks for your attention! Actually, we should always build the model with a resolution of 512x512, no matter what the input size is. I have fixed this problem. Please pull the latest version.

Although our Places model can handle 1024x1024 images, we suggest maintaining resolution consistency during
training and testing yields better visual quality. We have quantitatively compared the generalization ability to a higher resolution between our model and LaMa-Big (see supplementary file), finding the visual results of our model and LaMa-Big are not as good as 512x512 images, despite higher evaluation performance of our method.

**Comment by Matthewhouch** [comment]
Problem fixed! 
And thanks a lot for your prompt reply!
The results of inpainting 1024 images with 512 pretrained model indeed is not as well as those inpaint 512 images, but still better than many other methods. Thanks again!

**Comment by herbiezhao** [comment]
Same problem with the latest code, when I set resolution 1024 or 2048.

**Comment by logan-markewich** [comment]
I get the same error as well, @Lifedecoder how did you get the model to run 1024 images?

**Comment by fenglinglwb** [comment]
The problem should be fixed now. Sorry for the unpleasant experience.
But as mentioned, our results at the resolution of 1024x1024 are not as good as 512x512 images.

**Comment by huytuong010101** [comment]
@loga
@fenglinglwb 
I got this error when run with 1536x1536 image, can you show me how to fix this :(
```
[/content/drive/MyDrive/inpainting/MAT-main/networks/basic_module.py](https://localhost:8080/#) in forward(self, x, style, noise_mode, gain)
    200             if noise_mode == 'const':
    201                 noise = self.noise_const * self.noise_strength
--> 202             x = x + noise
    203 
    204         act_gain = self.act_gain * gain

RuntimeError: The size of tensor a (48) must match the size of tensor b (16) at non-singleton dimension 3
```

**Comment by LongEarW** [comment]
> @loga @fenglinglwb I got this error when run with 1536x1536 image, can you show me how to fix this :(
> 
> ```
> [/content/drive/MyDrive/inpainting/MAT-main/networks/basic_module.py](https://localhost:8080/#) in forward(self, x, style, noise_mode, gain)
>     200             if noise_mode == 'const':
>     201                 noise = self.noise_const * self.noise_strength
> --> 202             x = x + noise
>     203 
>     204         act_gain = self.act_gain * gain
> 
> RuntimeError: The size of tensor a (48) must match the size of tensor b (16) at non-singleton dimension 3
> ```

I got similar error with 1024*1024 image, and set `--resolution 1024` helps.
