### ISSUE TITLE
check_ddp_consistency error

### ISSUE THREAD

**Issue by ImmortalSdm** [fenglinglwb/MAT#7]
`Traceback (most recent call last):
  File "/home/dmsheng/anaconda3/envs/lama/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/dmsheng/demo/image_inpainting/MAT/my_train.py", line 405, in subprocess_fn
    my_training_loop.training_loop(rank=rank, **args)
  File "/home/dmsheng/demo/image_inpainting/MAT/training/my_training_loop.py", line 404, in training_loop
    misc.check_ddp_consistency(module, ignore_regex=[r'.*\.w_avg', r'.*\.relative_position_index', r'.*\.avg_weight', r'.*\.attn_mask', r'.*\.resample_filter'])
  File "/home/dmsheng/demo/image_inpainting/MAT/torch_utils/misc.py", line 195, in check_ddp_consistency
    assert (nan_to_num(tensor) == nan_to_num(other)).all(), fullname
AssertionError: Generator.synthesis.first_stage.conv_first.conv.weight`
Thanks for your great work! I have no idea what 'check_ddp_consistency' function for. Any ideas to solve the problem?

**Comment by fenglinglwb** [comment]
The error indicates that the values of params/buffers are inconsistent across different GPUs or may contain nan numbers.

**Comment by ImmortalSdm** [comment]
I'm afraid is the first error, how to fix the inconsistency?

**Comment by fenglinglwb** [comment]
Have you made any modifications? If the error is raised by the inconsistency of buffer values, just add the buffer variables to the 'ignore_regex'. However, it seems that there is an error in Conv weights, which I have never met before. I suggest that you should first figure out the reason, inconsistency or nan values.

**Comment by ImmortalSdm** [comment]
> Have you made any modifications? If the error is raised by the inconsistency of buffer values, just add the buffer variables to the 'ignore_regex'. However, it seems that there is an error in Conv weights, which I have never met before. I suggest that you should first figure out the reason, inconsistency or nan values.
I've check the weight tensor, no nan or inf, perhaps the inconsistency, how to solve the problem?

**Comment by fenglinglwb** [comment]
I'm sorry I didn't encounter this problem. Did you use the right environment as suggested? If not, please have a try.

**Comment by ImmortalSdm** [comment]
Are your code based on StyleGAN2-Ada? I'm finding the same error in their issue. I'm trying to add new input data in dataset, and don't change the network. I've tried the same environment as you suggested, nothing change. I've also check the weight, no nan or inf. So i'm confusing what causes the inconsitency. If i need to change dataset and for example, using other mask data, anything i need to notice?

**Comment by fenglinglwb** [comment]
Yes, our code is based on the official StyleGAN2-Ada (PyTorch version). We adopted CelebA-HQ and Palces-Standard for experiments, using the provided mask generator. So far, nothing special to note.

**Comment by ImmortalSdm** [comment]
> Yes, our code is based on the official StyleGAN2-Ada (PyTorch version). We adopted CelebA-HQ and Palces-Standard for experiments, using the provided mask generator. So far, nothing special to note.

Thansk for your reply, i will try to figure out the problem.

**Comment by Lanxin1011** [comment]
> > Yes, our code is based on the official StyleGAN2-Ada (PyTorch version). We adopted CelebA-HQ and Palces-Standard for experiments, using the provided mask generator. So far, nothing special to note.
> 
> Thansk for your reply, i will try to figure out the problem.

Hello, sorry to bother you. Have you solved the problem yet? I've encountered the same one during the evaluation phase of the training process. Looking forward to your reply~
