### ISSUE TITLE
Train model for 50M images on Places365-Standard??

### ISSUE THREAD

**Issue by wennycooper** [fenglinglwb/MAT#74]
Hi, I've one question in the paper.
You mention that "we train our models for 50M images on Places365-Standard and 25M images on CelebA-HQ ..."
But the Places365-Standard have only 1.8 million train and 36000 validation images. 

Would you please explain that? 

Thanks.
Kevin Kuei

**Comment by fenglinglwb** [comment]
That means, in terms of Places365-Strandard, we trained our model using 50M samples by sampling on the 1.8M training images.

**Comment by wennycooper** [comment]
Got it. Thanks for the quick feedback!
