### ISSUE TITLE
How to determine the token is valid or invalid by mask? 

### ISSUE THREAD

**Issue by wennycooper** [fenglinglwb/MAT#75]
Hi, I've one more question.
For example, the patch size is 8*8 pixels.
In the mask image, parts of pixels(say, 20 pixels) corresponding to the patch are black, how do you determine this patch(token) is valid or invalid?

**Comment by fenglinglwb** [comment]
Once there is a masked pixel in a patch, we regard this patch as an invalid one.

**Comment by wennycooper** [comment]
Thank you!
