### ISSUE TITLE
Place365-Standard dataset?

### ISSUE THREAD

**Issue by wennycooper** [fenglinglwb/MAT#77]
Hi,
Thanks for the sharing of such a great paper.
 
We are trying to reproduce your training result. 
There are a few different packages in the Place365-Standard.
They are "high resolution images(aspect ratio is not fixed)", "small images (256x256)".

Which one were you using?

Kevin Kuei

**Comment by fenglinglwb** [comment]
We used high-resolution ones which have a minimum length of 512.

**Comment by wennycooper** [comment]
Thanks for the response.
