### ISSUE TITLE
Getting a non-pluralistic inpainting 

### ISSUE THREAD

**Issue by Ash920** [fenglinglwb/MAT#84]
Hello, can you please tell me which parameter to change so that I can get a non-pluralistic inpainting to an image. I have tried changing the "noise_mode" parameter but it did not work.
really appreciate your kind response.
Thanks,

**Comment by fenglinglwb** [comment]
Thanks for your interest. You could fix the input latent code and dropout patterns at
https://github.com/fenglinglwb/MAT/blob/d273d891ecdad2e1df106516423a75bc45b2d800/networks/mat.py#LL779C23-L779C45
and
https://github.com/fenglinglwb/MAT/blob/d273d891ecdad2e1df106516423a75bc45b2d800/networks/mat.py#L840

**Comment by Ash920** [comment]
That worked! thanks.
